# Generated by Django 2.2.10 on 2020-03-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('tracker', '0019_entries_fbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='fbid',
        ),
        migrations.AddField(
            model_name='entries',
            name='socialauth',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
