# Generated by Django 2.2.10 on 2020-03-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20200322_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='socialauth',
        ),
        migrations.AddField(
            model_name='entries',
            name='fbid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
